### ISSUE TITLE
图片下载零字节

### ISSUE THREAD

**Issue by luoei** [ares333/CurlMulti#27]
php环境：7.1

Warning: file_get_contents(): Filename cannot be empty in /xxx/php-curlmulti-master/src/Core.php on line 462

Warning: fopen(/xxx/php-curlmulti-master/demo/base/static/xxx/indoors/../uploads/allimg/161208/1-16120Q61432.jpg): failed to open stream: Too many open files in /xxx/php-curlmulti-master/src/AutoClone.php on line 224

**Comment by ares333** [comment]
修改linux ulimit最大文件句柄

**Comment by luoei** [comment]
按照您的设置，现在OK了。多谢
