### ISSUE TITLE
克隆网站到2G，一直没结束

### ISSUE THREAD

**Issue by luoei** [ares333/CurlMulti#29]
网站如下： http://www.jujiaobaby.com
PHP版本：7.2
OSX 版本：10.13.1
部分错误日志：
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2Fwz%2Fxiang%2Fid%2F9.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/a19/2f3/70d843e37b8152072481cbc4e3): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED]}s\xD3V\xD6\xFF\ef\xF8\x0Ew...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/a19/2f3/70d843e37b8152072481cbc4e3): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED]}s\xD3V\xD6\xFF\ef\xF8\x0Ew...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2Fwz%2Fxiang%2Fid%2F8.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2Fwz%2Fxiang%2Fid%2F8.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/6d9/28c/80a14279cfdbc8cc5276c5f405): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED]\xF9S\eG\xF6\xFF\xD9\xAE\xF2\xFF0...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/6d9/28c/80a14279cfdbc8cc5276c5f405): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED]\xF9S\eG\xF6\xFF\xD9\xAE\xF2\xFF0...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2FJujiao%2Fabout%2Fid%2F8.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2FJujiao%2Fabout%2Fid%2F8.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/199/21e/86909667f5f14b89bf1291a251): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xBD:ks\xDB\xC6\xB5\x9F\xA5\x19\xFD\x87\r...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/199/21e/86909667f5f14b89bf1291a251): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xBD:ks\xDB\xC6\xB5\x9F\xA5\x19\xFD\x87\r...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2FZuopin%2Fworks.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/clone/http_www.jujiaobaby.com/index.php？s=%2FHome%2FZuopin%2Fworks.html): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php:306
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 306, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(306): file_put_contents('/Users/luoei/Do...', '<!DOCTYPE html ...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(33): Ares333\Curl\HttpClone->onProcess(Array, Array)
#3 [internal function]: HttpCloneDemo->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(492): call_user_func(Array, Array, Array)
#5 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#6 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#7 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#8 {main}
E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/760/767/6be4aa0b78703abfb6f67785d8): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED\\}s\xDB\xC6\x99\xFF[\x9A\xD1w\xD8...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}

E_WARNING: ErrorException: file_put_contents(/Users/luoei/Downloads/php-curl-master-1/demo/output/cache/760/767/6be4aa0b78703abfb6f67785d8): failed to open stream: Too many open files in /Users/luoei/Downloads/php-curl-master-1/src/Curl.php:562
Stack trace:
#0 [internal function]: ErrorHandler::{closure}(2, 'file_put_conten...', '/Users/luoei/Do...', 562, Array)
#1 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(562): file_put_contents('/Users/luoei/Do...', 'x\x9C\xED\\}s\xDB\xC6\x99\xFF[\x9A\xD1w\xD8...', 2)
#2 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(499): Ares333\Curl\Curl->cache(Array, Array)
#3 /Users/luoei/Downloads/php-curl-master-1/src/Curl.php(331): Ares333\Curl\Curl->onProcess(Array, Array)
#4 /Users/luoei/Downloads/php-curl-master-1/src/HttpClone.php(124): Ares333\Curl\Curl->start()
#5 /Users/luoei/Downloads/php-curl-master-1/demo/www.jujiaobaby.com.php(75): Ares333\Curl\HttpClone->start()
#6 {main}

**Comment by ares333** [comment]
使用最新版本测试，某些旧版本需要手动关闭文件句柄。
