### ISSUE TITLE
请问添加任务之后，怎么获取抓取到的内容？

### ISSUE THREAD

**Issue by yundGo** [ares333/CurlMulti#32]
我用add方法，添加了一个任务，任务开始之后，会把抓取到的内容打印出来，但是执行成功后回调函数返回的数据里面没有抓取到的内容字段。请问我要怎么获得抓取的内容，不需要打印出来？

**Comment by ares333** [comment]
[demo/basic.php](../blob/master/demo/basic.php)
回调函数外的$responseCode是在回调函数中赋值，需要了解异步io、php回调、php引用。

**Comment by yundGo** [comment]
@ares333 明白了，非常感谢
