### ISSUE TITLE
The args parameter is set to unavailable.

### ISSUE THREAD

**Issue by 123xuwu** [ares333/CurlMulti#35]
The args parameter is set, but it is not received by the backend.
This is the code：
Ares333\Curl\Curl;
$curl = new Curl();
$curl->add(
    array(
        'opt' => array(
            CURLOPT_URL => 'http://127.0.0.1:8080/cs/request.php',
            CURLOPT_RETURNTRANSFER => true
        ),
        'args' => array(
            "word"=>"你好"
        )
    ),
    function ($r, $args) {
        echo "Request success for " . $r['info']['url'] . "<br />";
        echo "<br />Header info:<br />";
        print_r($r['info']);
        echo "<br />Raw header:<br />";
        print_r($r['header']);
        echo "<br />Args:<br />";
        print_r($args);
        echo "<br /><br />Body size:<br />";
        echo strlen($r['body']) . ' bytes';
        echo "<br />";
        echo "<br />Body:<br />";
        echo "<pre>".htmlspecialchars($r['body'])."</pre>";
        // print_r($r);
    });
$curl->start();

This is the return:
GET：Array
(
)

**Comment by bgg10** [comment]
您好，邮件已收到，尽快给您回复。

**Comment by ares333** [comment]
url换成 https://www.baidu.com 之后没法发现问题

**Comment by ares333** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/7401387/199489400-5f9b4f43-190d-47f1-875a-41c73140fa25.png">
